version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 3003:3003
    depends_on:
      - prisma
    environment:
      DATABASE_URL: postgres://postgres:${PG_PASSWORD}@pg_db:5432/postgres
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env

  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: pg_db
            port: 5432
            user: postgres
            password: ${PG_PASSWORD}
            database: pg_db
            migrations: true
            rawAccess: true

  db:
    container_name: pg_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
